//! # c2pa-lite
//!
//! Pragmatic [C2PA content credentials](https://c2pa.org/specifications/)
//! for AI image and video generators that don't yet have provenance
//! signaling. Provides two layers:
//!
//! 1. **Signed manifest** — a JSON-LD-shaped attribution claim signed
//!    with the producer's key. The signing primitives delegate to
//!    upstream [`c2pa-rs`](https://github.com/contentauth/c2pa-rs)
//!    when the `upstream` feature is enabled; the scaffold provides
//!    a deterministic placeholder so the API surface compiles.
//! 2. **Soft-binding watermark** — an invisible, robust pattern
//!    embedded in the image bytes that survives common transformations
//!    (re-encoding, mild crops, mild rotations). The scaffold sketches
//!    the API; the embedder/extractor lands later.
//!
//! ## Status
//!
//! In Progress (Wave 5, re-promoted from Deferred per the goal naming
//! prevention explicitly). The previous deferral reasoning — moving
//! research target on watermark removal, open-ended hosting burden —
//! still holds for the watermark layer. The manifest layer is
//! tractable now because upstream c2pa-rs handles the heavy lifting.
//!
//! ## Threat model
//!
//! C2PA provenance signals are not a defense; they are a label.
//! Adversaries can strip them. The value is in legitimate workflows
//! where a downstream verifier can confirm the asset came from a
//! known producer and was generated as claimed. Use alongside (not
//! instead of) content classifiers and hash matching.

#![deny(unsafe_op_in_unsafe_fn)]
#![warn(missing_docs)]
#![warn(rust_2018_idioms)]

use std::path::Path;

/// Errors returned by c2pa-lite.
#[derive(Debug, thiserror::Error)]
pub enum C2paError {
    /// The input file could not be read.
    #[error("io error: {0}")]
    Io(String),
    /// The key material was invalid.
    #[error("invalid key material")]
    InvalidKey,
    /// The manifest failed verification.
    #[error("manifest verification failed: {0}")]
    ManifestInvalid(String),
    /// The watermark could not be embedded or extracted.
    #[error("watermark error: {0}")]
    Watermark(String),
    /// The requested operation is not yet implemented in this scaffold.
    #[error("not implemented in scaffold: {0}")]
    NotImplemented(&'static str),
}

/// A signed C2PA manifest claim.
///
/// In the scaffold this carries the structured fields without the
/// actual JWS signature. The upstream-feature build will round-trip
/// through `c2pa-rs` for production-grade signatures.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestClaim {
    /// Stable identifier (usually a UUID).
    pub claim_id: String,
    /// Human-readable producer name.
    pub producer: String,
    /// Whether the asset was generated by AI.
    pub ai_generated: bool,
    /// Name of the generator (e.g. "Stable Diffusion XL 1.0").
    pub generator: Option<String>,
    /// Free-form metadata fields.
    pub metadata: Vec<(String, String)>,
}

impl ManifestClaim {
    /// Build a new claim with the minimum required fields.
    pub fn new(
        claim_id: impl Into<String>,
        producer: impl Into<String>,
        ai_generated: bool,
    ) -> Self {
        Self {
            claim_id: claim_id.into(),
            producer: producer.into(),
            ai_generated,
            generator: None,
            metadata: Vec::new(),
        }
    }

    /// Attach a generator name (e.g. for AI assets).
    pub fn with_generator(mut self, generator: impl Into<String>) -> Self {
        self.generator = Some(generator.into());
        self
    }

    /// Add a metadata field.
    pub fn with_metadata(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.metadata.push((key.into(), value.into()));
        self
    }

    /// Serialize to the deterministic canonical form used for signing.
    pub fn to_canonical(&self) -> String {
        let mut s = String::new();
        s.push_str("claim_id=");
        s.push_str(&self.claim_id);
        s.push('\n');
        s.push_str("producer=");
        s.push_str(&self.producer);
        s.push('\n');
        s.push_str("ai_generated=");
        s.push_str(if self.ai_generated { "true" } else { "false" });
        s.push('\n');
        if let Some(g) = &self.generator {
            s.push_str("generator=");
            s.push_str(g);
            s.push('\n');
        }
        let mut sorted_meta = self.metadata.clone();
        sorted_meta.sort();
        for (k, v) in sorted_meta {
            s.push_str("meta:");
            s.push_str(&k);
            s.push('=');
            s.push_str(&v);
            s.push('\n');
        }
        s
    }
}

/// A signed asset: the source path, the attribution claim, and an Ed25519
/// signature over the claim's canonical form.
///
/// The signature is real (Ed25519, RFC 8032). The full C2PA manifest
/// embedding into the asset bytes lands behind the `upstream` feature.
#[derive(Debug, Clone)]
pub struct SignedAsset {
    /// The path the asset was loaded from.
    pub source_path: String,
    /// The claim associated with the asset.
    pub claim: ManifestClaim,
    /// The Ed25519 signature (64 bytes) over the claim's canonical form.
    pub signature: Vec<u8>,
}

/// Sign a claim for an asset on disk, producing an Ed25519 signature over
/// the claim's canonical form.
///
/// `signing_key_seed` is a 32-byte Ed25519 seed (the private key). Use
/// [`verifying_key_from_seed`] to derive the public key a verifier needs.
/// The full C2PA manifest embedding (JWS via c2pa-rs) lands behind the
/// `upstream` feature; this signs the attribution claim itself, which is
/// the part a downstream verifier checks.
///
/// # Errors
///
/// [`C2paError::InvalidKey`] if the seed is not exactly 32 bytes;
/// [`C2paError::Io`] if the path is not valid UTF-8.
pub fn sign_image(
    path: impl AsRef<Path>,
    claim: ManifestClaim,
    signing_key_seed: &[u8],
) -> Result<SignedAsset, C2paError> {
    use ed25519_dalek::{Signer, SigningKey};

    let source_path = path
        .as_ref()
        .to_str()
        .ok_or_else(|| C2paError::Io("non-utf8 path".into()))?
        .to_string();

    let seed: [u8; 32] = signing_key_seed
        .try_into()
        .map_err(|_| C2paError::InvalidKey)?;
    let signing_key = SigningKey::from_bytes(&seed);
    let signature = signing_key.sign(claim.to_canonical().as_bytes());

    Ok(SignedAsset {
        source_path,
        claim,
        signature: signature.to_bytes().to_vec(),
    })
}

/// Derive the 32-byte Ed25519 verifying (public) key from a 32-byte seed.
///
/// # Errors
///
/// [`C2paError::InvalidKey`] if the seed is not exactly 32 bytes.
pub fn verifying_key_from_seed(signing_key_seed: &[u8]) -> Result<Vec<u8>, C2paError> {
    use ed25519_dalek::SigningKey;

    let seed: [u8; 32] = signing_key_seed
        .try_into()
        .map_err(|_| C2paError::InvalidKey)?;
    Ok(SigningKey::from_bytes(&seed)
        .verifying_key()
        .to_bytes()
        .to_vec())
}

/// Verify an Ed25519 signature over a claim's canonical form.
///
/// Returns `Ok(())` if `signature` is valid for `verifying_key` (a 32-byte
/// Ed25519 public key), or [`C2paError::ManifestInvalid`] if it does not
/// match — including when the claim was modified after signing.
///
/// # Errors
///
/// [`C2paError::InvalidKey`] for a malformed key; [`C2paError::ManifestInvalid`]
/// for a wrong-length or non-matching signature.
pub fn verify_signature(
    claim: &ManifestClaim,
    signature: &[u8],
    verifying_key: &[u8],
) -> Result<(), C2paError> {
    use ed25519_dalek::{Signature, VerifyingKey};

    let vk_bytes: [u8; 32] = verifying_key
        .try_into()
        .map_err(|_| C2paError::InvalidKey)?;
    let vk = VerifyingKey::from_bytes(&vk_bytes).map_err(|_| C2paError::InvalidKey)?;
    let sig_bytes: [u8; 64] = signature
        .try_into()
        .map_err(|_| C2paError::ManifestInvalid("signature must be 64 bytes".into()))?;
    let sig = Signature::from_bytes(&sig_bytes);

    vk.verify_strict(claim.to_canonical().as_bytes(), &sig)
        .map_err(|e| C2paError::ManifestInvalid(e.to_string()))
}

/// Soft-binding watermark embedder.
///
/// Embeds an invisible, robust pattern in image bytes that survives
/// common transformations. The pattern carries a short payload (the
/// manifest's claim_id, typically) so a downstream verifier can
/// locate the corresponding manifest even if the file metadata was
/// stripped.
pub mod watermark {
    use super::C2paError;

    /// Embed a payload as a soft-binding watermark into PNG/JPEG bytes.
    ///
    /// Scaffold: returns NotImplemented. The watermark scheme is the
    /// part of the design most exposed to research drift; we wire it
    /// up once a robust scheme has stabilized in the literature.
    pub fn embed(_image_bytes: &[u8], _payload: &[u8]) -> Result<Vec<u8>, C2paError> {
        Err(C2paError::NotImplemented("watermark::embed"))
    }

    /// Extract a payload from watermarked bytes, if present.
    pub fn extract(_image_bytes: &[u8]) -> Result<Option<Vec<u8>>, C2paError> {
        Err(C2paError::NotImplemented("watermark::extract"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claim_to_canonical_includes_required_fields() {
        let claim = ManifestClaim::new("c-1", "MyProducer", true);
        let canonical = claim.to_canonical();
        assert!(canonical.contains("claim_id=c-1"));
        assert!(canonical.contains("producer=MyProducer"));
        assert!(canonical.contains("ai_generated=true"));
    }

    #[test]
    fn claim_canonical_is_deterministic() {
        let claim = ManifestClaim::new("c-1", "Producer", false)
            .with_metadata("k1", "v1")
            .with_metadata("k2", "v2");
        let again = ManifestClaim::new("c-1", "Producer", false)
            .with_metadata("k2", "v2") // different insertion order
            .with_metadata("k1", "v1");
        assert_eq!(claim.to_canonical(), again.to_canonical());
    }

    // A fixed 32-byte Ed25519 seed for deterministic tests.
    const TEST_SEED: [u8; 32] = [7u8; 32];

    #[test]
    fn sign_image_produces_64_byte_signature() {
        let claim = ManifestClaim::new("c-1", "P", true).with_generator("Test Gen v1");
        let asset = sign_image("/tmp/dummy.png", claim.clone(), &TEST_SEED).unwrap();
        assert_eq!(asset.claim, claim);
        assert_eq!(asset.signature.len(), 64);
    }

    #[test]
    fn sign_image_signature_is_deterministic() {
        // Ed25519 (RFC 8032) signatures are deterministic for the same key+msg.
        let claim = ManifestClaim::new("c-1", "P", true);
        let a = sign_image("/tmp/x.png", claim.clone(), &TEST_SEED).unwrap();
        let b = sign_image("/tmp/x.png", claim, &TEST_SEED).unwrap();
        assert_eq!(a.signature, b.signature);
    }

    #[test]
    fn sign_then_verify_roundtrip() {
        let claim = ManifestClaim::new("c-1", "Producer", true).with_generator("SDXL");
        let asset = sign_image("/tmp/x.png", claim.clone(), &TEST_SEED).unwrap();
        let vk = verifying_key_from_seed(&TEST_SEED).unwrap();
        assert!(verify_signature(&asset.claim, &asset.signature, &vk).is_ok());
    }

    #[test]
    fn verify_rejects_tampered_claim() {
        let claim = ManifestClaim::new("c-1", "Producer", true);
        let asset = sign_image("/tmp/x.png", claim, &TEST_SEED).unwrap();
        let vk = verifying_key_from_seed(&TEST_SEED).unwrap();
        let tampered = ManifestClaim::new("c-1", "Attacker", true);
        assert!(verify_signature(&tampered, &asset.signature, &vk).is_err());
    }

    #[test]
    fn verify_rejects_wrong_key() {
        let claim = ManifestClaim::new("c-1", "Producer", true);
        let asset = sign_image("/tmp/x.png", claim.clone(), &TEST_SEED).unwrap();
        let other_vk = verifying_key_from_seed(&[9u8; 32]).unwrap();
        assert!(verify_signature(&asset.claim, &asset.signature, &other_vk).is_err());
    }

    #[test]
    fn sign_rejects_bad_seed_length() {
        let claim = ManifestClaim::new("c-1", "P", true);
        let err = sign_image("/tmp/x.png", claim, b"too-short").unwrap_err();
        assert!(matches!(err, C2paError::InvalidKey));
    }

    #[test]
    fn watermark_embed_returns_not_implemented() {
        let result = watermark::embed(b"png bytes", b"payload");
        assert!(matches!(result, Err(C2paError::NotImplemented(_))));
    }
}
