//! # c2pa-lite
//!
//! Pragmatic [C2PA content credentials](https://c2pa.org/specifications/)
//! for AI image and video generators that don't yet have provenance
//! signaling. Provides two layers:
//!
//! 1. **Signed manifest** — a JSON-LD-shaped attribution claim signed
//!    with the producer's key. The signing primitives delegate to
//!    upstream [`c2pa-rs`](https://github.com/contentauth/c2pa-rs)
//!    when the `upstream` feature is enabled; the scaffold provides
//!    a deterministic placeholder so the API surface compiles.
//! 2. **Soft-binding watermark** — an invisible, robust pattern
//!    embedded in the image bytes that survives common transformations
//!    (re-encoding, mild crops, mild rotations). The scaffold sketches
//!    the API; the embedder/extractor lands later.
//!
//! ## Status
//!
//! In Progress (Wave 5, re-promoted from Deferred per the goal naming
//! prevention explicitly). The previous deferral reasoning — moving
//! research target on watermark removal, open-ended hosting burden —
//! still holds for the watermark layer. The manifest layer is
//! tractable now because upstream c2pa-rs handles the heavy lifting.
//!
//! ## Threat model
//!
//! C2PA provenance signals are not a defense; they are a label.
//! Adversaries can strip them. The value is in legitimate workflows
//! where a downstream verifier can confirm the asset came from a
//! known producer and was generated as claimed. Use alongside (not
//! instead of) content classifiers and hash matching.

#![deny(unsafe_op_in_unsafe_fn)]
#![warn(missing_docs)]
#![warn(rust_2018_idioms)]

use std::path::Path;

/// Errors returned by c2pa-lite.
#[derive(Debug, thiserror::Error)]
pub enum C2paError {
    /// The input file could not be read.
    #[error("io error: {0}")]
    Io(String),
    /// The key material was invalid.
    #[error("invalid key material")]
    InvalidKey,
    /// The manifest failed verification.
    #[error("manifest verification failed: {0}")]
    ManifestInvalid(String),
    /// The watermark could not be embedded or extracted.
    #[error("watermark error: {0}")]
    Watermark(String),
    /// The requested operation is not yet implemented in this scaffold.
    #[error("not implemented in scaffold: {0}")]
    NotImplemented(&'static str),
}

/// A signed C2PA manifest claim.
///
/// In the scaffold this carries the structured fields without the
/// actual JWS signature. The upstream-feature build will round-trip
/// through `c2pa-rs` for production-grade signatures.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestClaim {
    /// Stable identifier (usually a UUID).
    pub claim_id: String,
    /// Human-readable producer name.
    pub producer: String,
    /// Whether the asset was generated by AI.
    pub ai_generated: bool,
    /// Name of the generator (e.g. "Stable Diffusion XL 1.0").
    pub generator: Option<String>,
    /// Free-form metadata fields.
    pub metadata: Vec<(String, String)>,
}

impl ManifestClaim {
    /// Build a new claim with the minimum required fields.
    pub fn new(
        claim_id: impl Into<String>,
        producer: impl Into<String>,
        ai_generated: bool,
    ) -> Self {
        Self {
            claim_id: claim_id.into(),
            producer: producer.into(),
            ai_generated,
            generator: None,
            metadata: Vec::new(),
        }
    }

    /// Attach a generator name (e.g. for AI assets).
    pub fn with_generator(mut self, generator: impl Into<String>) -> Self {
        self.generator = Some(generator.into());
        self
    }

    /// Add a metadata field.
    pub fn with_metadata(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.metadata.push((key.into(), value.into()));
        self
    }

    /// Serialize to the deterministic canonical form used for signing.
    pub fn to_canonical(&self) -> String {
        let mut s = String::new();
        s.push_str("claim_id=");
        s.push_str(&self.claim_id);
        s.push('\n');
        s.push_str("producer=");
        s.push_str(&self.producer);
        s.push('\n');
        s.push_str("ai_generated=");
        s.push_str(if self.ai_generated { "true" } else { "false" });
        s.push('\n');
        if let Some(g) = &self.generator {
            s.push_str("generator=");
            s.push_str(g);
            s.push('\n');
        }
        let mut sorted_meta = self.metadata.clone();
        sorted_meta.sort();
        for (k, v) in sorted_meta {
            s.push_str("meta:");
            s.push_str(&k);
            s.push('=');
            s.push_str(&v);
            s.push('\n');
        }
        s
    }
}

/// A signed asset: the original bytes plus the attached manifest.
///
/// In the scaffold the signature is a placeholder (the canonical form
/// hashed with a stub). Production builds use c2pa-rs.
#[derive(Debug, Clone)]
pub struct SignedAsset {
    /// The path the asset was loaded from.
    pub source_path: String,
    /// The claim associated with the asset.
    pub claim: ManifestClaim,
    /// The placeholder signature.
    pub signature: Vec<u8>,
}

/// Sign an asset on disk with the given claim.
///
/// Scaffold: produces a deterministic placeholder signature so the API
/// surface is exercised. Real signing lands behind the `upstream`
/// feature, delegating to c2pa-rs.
pub fn sign_image(
    path: impl AsRef<Path>,
    claim: ManifestClaim,
    _key_pem: &[u8],
) -> Result<SignedAsset, C2paError> {
    let path_ref = path.as_ref();
    let source_path = path_ref
        .to_str()
        .ok_or_else(|| C2paError::Io("non-utf8 path".into()))?
        .to_string();

    let canonical = claim.to_canonical();
    let placeholder_signature = stub_signature(canonical.as_bytes());

    Ok(SignedAsset {
        source_path,
        claim,
        signature: placeholder_signature,
    })
}

/// Verification result.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerificationResult {
    /// True if the asset bears a structurally valid c2pa-lite manifest.
    pub valid: bool,
    /// The claim recovered from the asset, if verification succeeded.
    pub claim: Option<ManifestClaim>,
}

/// Verify a signed asset.
///
/// Scaffold: returns NotImplemented. The real verification path lands
/// once the manifest is embedded in the asset bytes (currently it's
/// only attached in memory).
pub fn verify(_path: impl AsRef<Path>) -> Result<VerificationResult, C2paError> {
    Err(C2paError::NotImplemented("verify"))
}

/// Soft-binding watermark embedder.
///
/// Embeds an invisible, robust pattern in image bytes that survives
/// common transformations. The pattern carries a short payload (the
/// manifest's claim_id, typically) so a downstream verifier can
/// locate the corresponding manifest even if the file metadata was
/// stripped.
pub mod watermark {
    use super::C2paError;

    /// Embed a payload as a soft-binding watermark into PNG/JPEG bytes.
    ///
    /// Scaffold: returns NotImplemented. The watermark scheme is the
    /// part of the design most exposed to research drift; we wire it
    /// up once a robust scheme has stabilized in the literature.
    pub fn embed(_image_bytes: &[u8], _payload: &[u8]) -> Result<Vec<u8>, C2paError> {
        Err(C2paError::NotImplemented("watermark::embed"))
    }

    /// Extract a payload from watermarked bytes, if present.
    pub fn extract(_image_bytes: &[u8]) -> Result<Option<Vec<u8>>, C2paError> {
        Err(C2paError::NotImplemented("watermark::extract"))
    }
}

// Deterministic placeholder signature so the scaffold round-trips.
// NOT cryptographic — produces a length-32 byte vector hashing the
// input via a simple sum-of-bytes prefix. The `upstream` feature
// replaces this with the c2pa-rs signing path.
fn stub_signature(canonical: &[u8]) -> Vec<u8> {
    let mut out = vec![0u8; 32];
    for (i, b) in canonical.iter().enumerate() {
        out[i % 32] = out[i % 32].wrapping_add(*b);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claim_to_canonical_includes_required_fields() {
        let claim = ManifestClaim::new("c-1", "MyProducer", true);
        let canonical = claim.to_canonical();
        assert!(canonical.contains("claim_id=c-1"));
        assert!(canonical.contains("producer=MyProducer"));
        assert!(canonical.contains("ai_generated=true"));
    }

    #[test]
    fn claim_canonical_is_deterministic() {
        let claim = ManifestClaim::new("c-1", "Producer", false)
            .with_metadata("k1", "v1")
            .with_metadata("k2", "v2");
        let again = ManifestClaim::new("c-1", "Producer", false)
            .with_metadata("k2", "v2") // different insertion order
            .with_metadata("k1", "v1");
        assert_eq!(claim.to_canonical(), again.to_canonical());
    }

    #[test]
    fn sign_image_produces_signature() {
        let claim = ManifestClaim::new("c-1", "P", true).with_generator("Test Gen v1");
        let asset = sign_image("/tmp/dummy.png", claim.clone(), b"stub-key").unwrap();
        assert_eq!(asset.claim, claim);
        assert_eq!(asset.signature.len(), 32);
    }

    #[test]
    fn sign_image_signature_deterministic_for_same_claim() {
        let claim = ManifestClaim::new("c-1", "P", true);
        let a = sign_image("/tmp/x.png", claim.clone(), b"k").unwrap();
        let b = sign_image("/tmp/x.png", claim, b"k").unwrap();
        assert_eq!(a.signature, b.signature);
    }

    #[test]
    fn verify_returns_not_implemented_in_scaffold() {
        let result = verify("/tmp/x.png");
        assert!(matches!(result, Err(C2paError::NotImplemented(_))));
    }

    #[test]
    fn watermark_embed_returns_not_implemented() {
        let result = watermark::embed(b"png bytes", b"payload");
        assert!(matches!(result, Err(C2paError::NotImplemented(_))));
    }
}
